export const SET_AUTH_STATE = 'SET_AUTH_STATE';
export const SET_SID = 'SET_SID';
export const SET_NAVIGATION_VISIBILITY = 'SET_NAVIGATION_VISIBILITY';

export const SET_HISTORY = 'SET_HISTORY';
export const SET_FAVORITES_MUSIC = 'SET_FAVORITES_MUSIC';
export const SET_LOADER = 'SET_LOADER';
export const SELECT_MUSIC = 'SELECT_MUSIC';
export const SET_SEACTH_TEXT = 'SET_SEACTH_TEXT';

export const SET_RADIO_PLAYS = 'SET_RADIO_PLAYS'
export const SET_MUSIC_PLAYS = 'SET_MUSIC_PLAYS'